version: 2
jobs:
  build-and-test-android:
    docker:
      - image: circleci/android:api-28-node

    steps:
      - checkout

      - run:
          name: Build Android
          working_directory: native/android
          command: ./gradlew assembleDebug testDebugUnitTest

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test-android
